### ISSUE TITLE
How to delete repository from private registry?

### ISSUE THREAD

**Issue by juicefoods** [docker/docker-registry#45]
I was wondering how to delete a repository from my private registry? As I searched online there is no apparent way to do it. Thanks for you help.

**Comment by schmunk42** [comment]
+1

**Comment by szaffarano** [comment]
+1

**Comment by ankushagarwal** [comment]
+1 My registry size is getting out of control. I want to delete old images from the registry. There is no way to do this via API today.

**Comment by murali44** [comment]
+1

**Comment by kiwenlau** [comment]
+1

**Comment by svenkroll** [comment]
+1

**Comment by mrh666** [comment]
+2!

**Comment by stevvooe** [comment]
@ankushagarwal when you say your registry size is out of control, what size of data you referring to? How big is too much?

**Comment by ripienaar** [comment]
+1, am using https://gist.github.com/shepmaster/53939af82a51e3aa0cd6 now to clean orphaned stuff from the registry, having it happen magically would be great

**Comment by ankushagarwal** [comment]
@stevvooe : I am running the registry locally on my Mac in boot2docker with 50GB space and it ran out of space (Yes, I pushed a lot of images each about 1G in size).

**Comment by ankushagarwal** [comment]
I have switched to Quay.io's private registry for now which has a nice API to delete tags (It then deletes all images which are not reachable by any tags).

**Comment by bacongobbler** [comment]
I asked @stevvooe 2 weeks ago about this issue. AFAIK it looks like this will be resolved with the v2 implementation of the registry: https://botbot.me/freenode/docker-dev/2015-01-16/?msg=29800131&page=6

Without looking too far into the code, this could be resolved by tracking an image's refcount. If it is not a parent of any other image, then it's safe to say that the image could be removed without damaging the integrity of other images, though this could be a computationally expensive operation if we're talking about an image count somewhere in the 100k+ range.

**Comment by noren** [comment]
you can remove entire repository using curl:

curl -X DELETE <registry-url>/v1/repositories/<repository>/

to remove unused images you have to remove tag first:

$ curl -X DELETE <registry-url>/v1/repositories/<repository>/tags/<tag>

then run this script:
https://gist.github.com/kwk/c5443f2a1abcf0eb1eaa

on docker registy server, make sure you install 'jq' package first

**Comment by ankushagarwal** [comment]
I was just hoping that there was a inbuilt API to remove unused images,
instead of running an external script which needs maintenance.
ᐧ

On Fri, Feb 13, 2015 at 5:37 PM, Pawel <notifications@github.com> wrote:

> you can remove entire repository using curl:
>
> curl -X DELETE /v1/repositories//
>
> to remove unused images you have to remove tag first:
>
> $ curl -X DELETE /v1/repositories//tags/
>
> then run this script:
> https://gist.github.com/kwk/c5443f2a1abcf0eb1eaa
>
> on docker registy server, make sure you install 'jq' package first
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker-registry/issues/45#issuecomment-74244366>
> .
>



-- 
Ankush Agarwal
http://ankush.io
@ankushio <https://twitter.com/ankushio>

*There are 10 types of people in this world. Those who understand binary
and those who don't.*

**Comment by dmp42** [comment]
@ankushagarwal 
Addressing this is part of the new golang-registry (https://github.com/docker/distribution).

**Comment by robdbirch** [comment]
+1 it shouldn't be this hard

**Comment by nandarajxxx** [comment]
how to create private repository using docker api?
I have created registry using docker api by default it is public .
import requests
import json
from requests.auth import HTTPBasicAuth
data=[{"id":"8c2e06607696"}]
#data=json.dumps(data)
headers={'content-type':'application/json','Accept':'application/json','X-Docker-Token': 'true'}
url='http://index.docker.io/v1/repositories/nandaraj/busynew/'
r=requests.put(url,data=json.dumps(data),headers=headers,auth=HTTPBasicAuth('nandaraj', '12345'))
this is my code.By executing the above code repository is created a public .How to create a private repository using docker api?

**Comment by mindscratch** [comment]
@nandarajxxx I believe your question would be better suited on IRC, the Google Group or Stackoverflow. See the [community](https://www.docker.com/community/participate/) page for links to those community resources.

**Comment by nandarajxxx** [comment]
Thank You

**Comment by schmunk42** [comment]
As a workaround you could also use this [docker image](https://registry.hub.docker.com/u/konradkleine/docker-registry-frontend/), which offers a delete button for a repo.

**Comment by vincentvanouytsel** [comment]
@schmunk42 That doesn't remove the images from the storage, does it?

**Comment by schmunk42** [comment]
@vincentvanouytsel Uh, to be honest, I didn't check that, sorry. I just saw that the image is not listed anymore.

**Comment by vincentvanouytsel** [comment]
@schmunk42 I don't think it does. A workaround for this issue could be removing the tags (with the delete button) and then run [this](https://gist.github.com/kwk/c5443f2a1abcf0eb1eaa)  script. 
This should remove the untagged images from your storage.

**Comment by dacay** [comment]
+1

**Comment by Zolmeister** [comment]
+1

**Comment by jadedfire** [comment]
are any of the four mentioned potential solutions being looked at? (https://github.com/docker/distribution/blob/master/ROADMAP.md#deletes) it makes sense to me that coding the entire solution to meet the needs of the "lower common denominator among the storage drivers" can be likened to coding a solution around exceptions. one would think that with proper modularization, the software could adapt to specific deployments and act accordingly. for example, if deployed to a single node for development purposes, and leverages the OS filesystem, the system should load an "OS driver" that could manage deletes rather easily.

**Comment by stevvooe** [comment]
@jadedfire Yes, coding from an armchair is quite easy.

We are indeed looking into this set of solutions. There are a number of ways a registry can be deployed and we'd like to have a solution that works well for everyone, rather than restricting deletion to a narrow set of deployments.

If you believe the current analysis is flawed, I welcome your proposal, an implementation or any modifications that would help us to achieve this.

**Comment by ripienaar** [comment]
@stevvooe classy.

**Comment by stevvooe** [comment]
@ripienaar To help others understand why deletes are non-trivial, we put together an analysis. To have it dismissed off-hand, without consideration for the detailed points covered, is both insulting and inconsiderate, especially to those working at finding a solution.

If you or @jadedfire believe deletes to be straightforward, I invite you to contribute.

**Comment by ripienaar** [comment]
@stevvooe oh I see of course it's ok to be dismissive and belittling because it someone did it to you. Gotcha.

**Comment by stevvooe** [comment]
@ripienaar And how is what you are doing currently constructive? Just ignore my snark and let's move on.

We are implementing Stop-The-World GC in with https://github.com/docker/distribution/issues/743. This should help in a lot of simple deployments.

**Comment by petarmaric** [comment]
To be quite honest, this recent discussion is just one of the examples why I have much more respect for the Django project and its community than Docker. 

You really need to review your community guidelines, if you wish to have respect from and within the community.

**Comment by dmp42** [comment]
Hi all,

This exchange is not productive IMHO.

You are right @petarmaric, we should handle things in a better way.
Admittedly, it's not always easy, and admittedly, sometimes we suck at it.

Mind you, I believe we are successful at it most of the time, and you will find out that https://github.com/docker/distribution is indeed a place where constructive input and fast moving development happens, for the benefit of everybody.

Let me remind a couple of things to all people here:
- this repo here is clearly marked as deprecated, and has been for more than six months, and I'm still wondering why people would keep commenting here while this is plastered all over the repo, and while I myself barely read notifications anymore (and please check https://github.com/docker/docker-registry/graphs/contributors before assuming I'm just a random joe around here). _This here_ is the home of the legacy python, v1-protocol registry - no discussion or bug report is likely to lead to any other response than: please move to the v2 protocol based, golang implementation (here again: https://github.com/docker/distribution)
- priorities in an open-source project are driven by the willingness of people who actually write code. If you don't write code, that's perfectly ok, and you are definitely an important part of the community, and yes, your input is definitely the basis on top of which we are building the development effort, but now: blind, serial +1s, or blanket statements about what is supposedly easy to do are definitely not going to lead to a magical resolution - on the contrary, these are just adding to the developers frustration, especially when plenty of discussion already took place
- if you are still an active user of the v1, python registry, there are plenty of home grown solutions to garbage collect your storage: please just click https://github.com/docker/docker-registry/issues?q=is%3Aopen+is%3Aissue+label%3Adelete and look around
- if you are interested in the v2 registry, please look around here:
  - https://github.com/docker/distribution/issues/743
  - https://github.com/docker/distribution/issues/422
  - https://github.com/docker/distribution/pull/508
  - https://github.com/docker/distribution/pull/572
  - https://github.com/docker/distribution/pull/677
  - and finally here: https://github.com/docker/distribution/blob/master/ROADMAP.md#deletes
- if you have some constructive feedback to provide as to why you need (?:API-delete|garbage-collection|specific-usecase), please do so, by expressing a clear, motivated use case, and be opened to suggestions to address your actual concerns. I can assure you that it will be taken into account.
- if your feedback is just "I need to delete wtf you morons delete is so important what are doing you are doing nothing", I can assure you I will close your ticket on sight
- if you still think the official contributors here suck at it, that's fair: again, you will find out that major contributions are made by the community, and your code will be reviewed in a timely and fair fashion

I would like to end this with a strong and positive note: a community is a whole, and you are an integral part of it. If someone is not acting up to your standards, be the bigger man and make this community better by easing the dialog instead of fueling a flame war.

I'm closing and locking this issue, and wish this message goes through all participants here.
