### ISSUE TITLE
NG: caching as a first class citizen

### ISSUE THREAD

**Issue by bshi** [docker/docker-registry#647]
Caching seems to be an important feature and it might be nice to elevate it to work out of the box in a registry cluster.  If content addressable storage is a goal (https://github.com/docker/docker-registry/issues/616#issuecomment-58526486), it seems https://github.com/golang/groupcache would be an ideal candidate as it's specifically designed for this class of distribution problem.

**Comment by stevvooe** [comment]
The next generation registry and the distribution project are making plans to ensure content addressability across layers and manifests. While there are no immediate plans to integrate groupcache, As the V2 registry currently stands, distribution can benefit directly from http caching. It follows that groupcache would only help in addition.

This issue is going to be closed. A Proposal and PR is welcome for groupcache integration in docker/distribution.
