### ISSUE TITLE
sqlalchemy preload s3 potential threading issue

### ISSUE THREAD

**Issue by silarsis** [docker/docker-registry#710]
SQLAlchemy enabled seems to require --preload in the gunicorn opts (else it complains about an initialisation failure). However, with --preload on, S3 appears to have threading issues (my understanding is that boto uses httplib which is not thread safe). We were seeing 403 authentication failures from S3 under load on arbitrary requests, consistent with threading problems. These translated to 504 errors from docker-registry to the client.

I suspect (but have not confirmed) that --preload means a single S3 connection is setup in advance and shared across threads. This failure exists in 0.8.1 and 0.9.0 at least (but 0.8.1 will run without --preload, where 0.9.0 was consistently failing to initialise sqlalchemy for us).

**Comment by dannyjlaurence** [comment]
+1 on the solution of don't provide ```-e SEARCH_BACKEND```

Just for the google searchers out there, we were getting 404's from S3, and then "Booting worker with pid: 38"

The client would hang after this happened. (trying to push an image, usually)

Would love a fix for this - we are unable to use a GUI front end for our repo because of this.
